services:
  - type: web
    name: al-tawseya-premium-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:AppHandler --bind 0.0.0.0:8000 --conf gunicorn.conf.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: GOOGLE_API_KEY
        value: AQ.Ab8RN6IkMeWn63b4GdXVIfOCWUZbnP-p9PRJfgpEATp91lTLwQ
